forge "http://forge.puppetlabs.com"
moduledir './modules/'

# The following are modules required to build the VMs. These will be installed
# into a './modules' directory which will be deleted after the bootstrap is
# applied.
#
# For modules that are published on the forge, the default is
#   to use the forge module. The git repos are added and commented
#   out purely for convenience.
# For modules that aren't published on the forge, we specify that the 
#   master branch from the corresponding git repo be used.
# To fetch a specific version of a forge module, use:
#   mod 'pltraining/rbac', '1.0.1'
# To fetch a ref (commit, branch, or tag) from a git repo, use:
#   mod 'bootstrap', 
#     :git => 'https://github.com/puppetlabs/pltraining-bootstrap'
#     :ref => 'ref-goes-here'
branch = ENV['STABLE_MODULES'] =~ /^(true|yes|y|Y)/ ? 'release' : 'master'
  

# mod 'bootstrap',
#   :git => 'https://github.com/puppetlabs/pltraining-bootstrap',
#   :ref => ENV['BOOTSTRAP_BRANCH'] || branch
#
mod 'bootstrap', 
  :git => 'https://github.com/greglarkin/pltraining-bootstrap',
  :ref => 'add-ciab-vagrant-support'

mod 'learning',
  :git => 'https://github.com/puppetlabs/pltraining-learning',
  :ref => ENV['LEARNING_BRANCH'] || branch

mod 'localrepo',
  :git => 'https://github.com/puppetlabs/pltraining-localrepo',
  :ref => ENV['LOCALREPO_BRANCH'] || branch

mod 'dockeragent',
  :git => 'https://github.com/puppetlabs/pltraining-dockeragent',
  :ref => ENV['DOCKERAGENT_BRANCH'] || branch

if branch == 'release'
  mod 'pltraining/classroom'
  mod 'pltraining/rbac', '0.0.4'
  mod 'pltraining/dirtree'
  mod 'pltraining/userprefs'
else
  mod 'classroom', 
    :git => 'https://github.com/puppetlabs/pltraining-classroom',
    :ref => ENV['CLASSROOM_BRANCH'] || 'master'
  mod 'rbac', 
    :git => 'https://github.com/puppetlabs/pltraining-rbac',
    :ref => ENV['RBAC_BRANCH'] || 'master'
  mod 'dirtree', 
    :git => 'https://github.com/puppetlabs/pltraining-dirtree',
    :ref => ENV['DIRTREE_BRANCH'] || 'master'
  mod 'userprefs', 
    :git => 'https://github.com/puppetlabs/pltraining-userprefs',
    :ref => ENV['USERPREFS_BRANCH'] || 'master'
end


mod 'puppetlabs/concat', '1.2.4'
#mod 'concat', 
#  :git => 'https://github.com/puppetlabs/puppetlabs-concat'

mod 'puppetlabs/stdlib', '4.7.0'
#mod 'stdlib', 
#  :git => 'https://github.com/puppetlabs/puppetlabs-stdlib'

mod 'puppetlabs/vcsrepo', '1.3.1'
#mod 'vcsrepo',
#  :git => 'https://github.com/puppetlabs/puppetlabs-vcsrepo'

mod 'stahnma/epel', '1.0.2'
#mod 'epel', 
#  :git => 'https://github.com/stahnma/puppet-module-epel'  

mod 'nanliu/staging', '1.0.3'
#mod 'staging', 
#  :git => 'https://github.com/nanliu/puppet-staging'  

mod 'puppetlabs/apache', '1.5.0'

mod 'jfryman/selinux'

# Dependencies for docker/beaker on Self paced
mod 'garethr/docker'
mod 'puppetlabs/apt'

# Dependencies for learning VM
mod 'jfryman/nginx', '0.2.7'
mod 'maestrodev/wget'
mod 'ajcrowe/supervisord'
mod 'puppet/nodejs'

# Dependencies for bootstrap
mod 'stahnma/epel'
mod 'pltraining/userprefs'
mod 'puppetlabs/pe_gem'
mod 'puppetlabs/mysql'
mod 'pltraining/dirtree'
mod 'jfryman/selinux'
mod 'binford2k/abalone'
mod 'garethr/docker'
mod 'razorsedge/network'
mod 'puppetlabs/stdlib'

# Dependencies for CIAB
mod 'puppetlabs/firewall'
mod 'puppetlabs/mysql'
mod 'puppet/virtualbox'
mod 'unibet/vagrant'

# Dependencies for userprefs
mod 'puppetlabs/chocolatey'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/registry'
mod 'stahnma/epel'

# Dependencies for mysql
mod 'puppet-staging'

mod 'razorsedge/network'
