forge "http://forge.puppetlabs.com"
moduledir './modules/'

# The following are modules required to build the VMs. These will be installed
# into a './modules' directory which will be deleted after the bootstrap is
# applied.
#
# For modules that are published on the forge, the default is
#   to use the forge module. The git repos are added and commented
#   out purely for convenience.
# For modules that aren't published on the forge, we specify that the 
#   master branch from the corresponding git repo be used.
# To fetch a specific version of a forge module, use:
#   mod 'pltraining/rbac', '1.0.1'
# To fetch a ref (commit, branch, or tag) from a git repo, use:
#   mod 'bootstrap', 
#     :git => 'https://github.com/puppetlabs/pltraining-bootstrap',
#     :ref => 'ref-goes-here'

mod 'bootstrap',
  :git => 'https://github.com/puppetlabs/pltraining-bootstrap',
  :ref => 'legacy'

mod 'localrepo',
  :git => 'https://github.com/puppetlabs/pltraining-localrepo'

mod 'dockeragent',
  :git => 'https://github.com/puppetlabs/pltraining-dockeragent'

mod 'pltraining/classroom',
  :git => 'https://github.com/puppetlabs/pltraining-classroom'

mod 'rbac', 
  :git => 'https://github.com/puppetlabs/pltraining-rbac'

mod 'puppetlabs/concat', '1.2.4'
#mod 'concat',
#  :git => 'https://github.com/puppetlabs/puppetlabs-concat'

mod 'puppetlabs/stdlib', '4.7.0'

mod 'puppetlabs/vcsrepo', '1.3.1'
#mod 'vcsrepo',
#  :git => 'https://github.com/puppetlabs/puppetlabs-vcsrepo'

mod 'stahnma/epel', '1.0.2'

mod 'nanliu/staging', '1.0.3'
#mod 'staging',
#  :git => 'https://github.com/nanliu/puppet-staging'

mod 'puppetlabs/apache', '1.5.0'

mod 'pltraining/puppetfactory'

# Dependencies for docker/beaker on Self paced
mod 'puppetlabs/apt'

# Dependencies for learning VM
mod 'puppet/nginx', '0.6.0'
mod 'puppetlabs/inifile'
mod 'maestrodev/wget'
mod 'ajcrowe/supervisord'
mod 'puppet/nodejs'

# Dependencies for bootstrap
mod 'pltraining/userprefs'
mod 'puppetlabs/pe_gem'
mod 'puppetlabs/mysql'
mod 'pltraining/dirtree'
mod 'jfryman/selinux'
mod 'binford2k/abalone'
mod 'garethr/docker'
mod 'razorsedge/network'
mod 'puppet/archive'
mod 'puppetlabs/powershell'
mod 'saz/sudo'

# Dependencies for CIAB
mod 'puppetlabs/firewall'
mod 'puppet/virtualbox'
mod 'unibet/vagrant'

# Dependencies for userprefs
mod 'puppetlabs/chocolatey'
mod 'puppetlabs/registry'

# Dependencies for classroom
mod 'arusso/stunnel'
mod 'dwerder/graphite'
mod 'dwerder/grafana'
mod 'fiddyspence/hash_file'
mod 'jordan/fileshare'
mod 'pltraining/showoff'
mod 'puppetlabs/git'
mod 'puppetlabs/ntp'
mod 'puppetlabs/pe_puppetserver_gem'
mod 'puppetlabs/puppetserver_gem'
mod 'zack/exports'
mod 'puppetlabs/acl'
mod 'puppetlabs/dsc'
mod 'puppetlabs/reboot'
mod 'puppetlabs/wsus_client'
mod 'badgerious/windows_env'
mod 'puppet/download_file'
mod 'puppet/iis'
mod 'puppet/windowsfeature'
mod 'attachmentgenie/ssh'
mod 'fiddyspence/sysctl'
mod 'puppetlabs/ruby'
mod 'puppetlabs/gcc'
mod 'croddy/make'
mod 'gentoo/portage'
mod 'zack/r10k'
mod 'hunner/wordpress'
mod 'puppetlabs/haproxy'
