# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

# load customizations, such as the pretty git prompt.
# comment this out to use your own customizations.
if [ -f /root/.bashrc.puppet ]; then
  . /root/.bashrc.puppet
fi

if [ -f /root/.extendingrc ]; then
  export PATH=/opt/puppet/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
else
  export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
fi
