name    'rcoleman-edu_bootstrap'
version '0.9.1'
source ''
author 'rcoleman'
license 'Apache License, Version 2.0'
summary 'Module to aid in Puppet EDU training environment creation'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
dependency 'ripienaar/concat', '>= 0.1.0'
