name    'pltraining-fundamentals'
version '1.4.2'
source 'https://github.com/puppetlabs/puppetlabs-training-bootstrap/tree/master/modules/fundamentals'
author 'pltraining'
license 'Apache License, Version 2.0'
summary 'Module to aid in Puppet EDU training environment creation'
description 'Important! This is not the module you are looking for
    unless you are a trainer teaching the Puppet Fundamentals course!
    - Configures and sets up classroom environment for Puppet Fundamentals trainings.'
project_page 'https://github.com/puppetlabs/puppetlabs-training-bootstrap/tree/master/modules/fundamentals'

dependency 'puppetlabs/concat', '>= 0.1.0'
dependency 'puppetlabs/vcsrepo', '>= 0.1.2'
dependency 'pltraining/userprefs'
dependency 'puppetlabs/ntp', '>= 3.0.1'
