# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Update the courseware contents if required
if [ ! -f ~/.complete ]
then
  echo "Updating sample content:"
  git clone https://github.com/puppetlabs/courseware-lms-content.git --quiet
  mv courseware-lms-content/modules/* /etc/puppetlabs/puppet/modules/
  mv courseware-lms-content/hiera/hiera.yaml /etc/puppetlabs/puppet/
  mv courseware-lms-content/hiera/hieradata /etc/puppetlabs/puppet/
  rm -rf courseware-lms-content
  touch ~/.complete
fi

# User specific aliases and functions
export PATH=/usr/local/bin:$PATH
