name    'pltraining-kickstand'
version '0.0.3'
source 'https://github.com/puppetlabs/puppetlabs-training-bootstrap/tree/master/modules/kickstand'
author 'pltraining'
license 'Apache License, Version 2.0'
summary 'Module to assist in the provisioning lab for the Advanced Puppet course'
description 'Important! This is not the module you are looking for
    unless you are a trainer teaching the Advanced Puppet course!
    - Required for the provisioning example and exercises.'
project_page 'https://github.com/puppetlabs/puppetlabs-training-bootstrap/tree/master/modules/kickstand'
