# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias vi=vim
#export TERM=ansi

# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

## uncomment for dev training:
#export PATH=/usr/src/puppet/sbin:/usr/src/puppet/bin:/usr/src/facter/bin:$PATH
#export RUBYLIB=/usr/src/puppet/lib:/usr/src/facter/lib:$RUBYLIB
