# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias vi=vim
alias nano=‘nano -E -T2 -i -w’
#export TERM=ansi

# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

## uncomment for dev training:
#export PATH=/opt/puppet/bin:$PATH
#export RUBYLIB=/opt/puppet/lib/ruby/site_ruby/1.8/puppet:/opt/puppet/lib/ruby/site_ruby/1.8/facter:$RUBYLIB
